Add CI/CD workflow to build & push to ECR

diff --git a/.github/workflows/ecr-build-push.yml b/.github/workflows/ecr-build-push.yml
--- a/.github/workflows/ecr-build-push.yml
+++ b/.github/workflows/ecr-build-push.yml
@@ -1,4 +1,4 @@
-name: CI - Buil & Push to ECR
+name: CI - Build & Push to ECR
 
 on:
   push:
@@ -22,8 +22,13 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
-      - name: Test AWS Credentials
-        run: aws sts get-caller-identity
+      - name: Debug AWS vars
+        run: |
+          echo "AWS_ACCESS_KEY_ID length: ${#AWS_ACCESS_KEY_ID}"
+          echo "AWS_SECRET_ACCESS_KEY length: ${#AWS_SECRET_ACCESS_KEY}"
+          echo "Region: $AWS_REGION"
+          aws sts get-caller-identity || echo "STS failed"
+
 
 
       - name: Login to Amazon ECR
